# Generated by Django 4.2.1 on 2023-05-13 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Przepis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('czas_przygotowania', models.IntegerField()),
                ('trudnosc', models.IntegerField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zdjecia/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przepisy.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('id_miary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przepisy.miary')),
            ],
        ),
        migrations.CreateModel(
            name='PrzepisSkladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.FloatField()),
                ('id_przepisu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przepisy.przepis')),
                ('id_skladnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przepisy.skladnik')),
            ],
        ),
    ]
