# Generated by Django 4.2.1 on 2023-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name_plural': 'Kategoria'},
        ),
        migrations.AlterModelOptions(
            name='miary',
            options={'verbose_name_plural': 'Miary'},
        ),
        migrations.AlterModelOptions(
            name='przepis',
            options={'verbose_name_plural': 'Przepis'},
        ),
        migrations.AlterModelOptions(
            name='przepisskladnik',
            options={'verbose_name_plural': 'PrzepisSkladnik'},
        ),
        migrations.AlterModelOptions(
            name='skladnik',
            options={'verbose_name_plural': 'Skladniki'},
        ),
    ]
