# Generated by Django 4.2.1 on 2023-05-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0002_alter_kategoria_options_alter_miary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepisskladnik',
            name='id_miary',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Przepisy.miary'),
        ),
    ]
