# Generated by Django 4.2.1 on 2023-05-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0003_przepisskladnik_id_miary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='miary',
            options={'verbose_name_plural': 'Miary_Ilośi'},
        ),
        migrations.AlterModelOptions(
            name='przepis',
            options={'verbose_name_plural': 'Przepisy'},
        ),
        migrations.AlterModelOptions(
            name='przepisskladnik',
            options={'verbose_name_plural': 'Przepisy_Skladnik'},
        ),
        migrations.RemoveField(
            model_name='przepis',
            name='kategoria',
        ),
        migrations.RemoveField(
            model_name='przepis',
            name='trudnosc',
        ),
        migrations.RemoveField(
            model_name='przepisskladnik',
            name='id_miary',
        ),
        migrations.RemoveField(
            model_name='skladnik',
            name='id_miary',
        ),
        migrations.AddField(
            model_name='przepis',
            name='kategorie',
            field=models.ManyToManyField(to='Przepisy.kategoria'),
        ),
        migrations.AddField(
            model_name='przepisskladnik',
            name='miara',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Przepisy.miary'),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='zdjecie_skl',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia_sklad/'),
        ),
    ]
