# Generated by Django 4.2.1 on 2023-05-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0004_alter_kategoria_options_alter_miary_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='miara',
            new_name='id_miary',
        ),
    ]
