# Generated by Django 4.2.1 on 2023-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0005_rename_miara_przepisskladnik_id_miary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='id_miary',
            new_name='miara',
        ),
        migrations.AddField(
            model_name='miary',
            name='skrot',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
