# Generated by Django 4.2.1 on 2023-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0006_rename_id_miary_przepisskladnik_miara_miary_skrot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przepis',
            old_name='czas_przygotowania',
            new_name='czas_przygotowania_w_minutach',
        ),
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='miara',
            new_name='id_miary',
        ),
        migrations.AddField(
            model_name='przepis',
            name='kalorie_na_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='przepisskladnik',
            name='kalorie_na_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skladnik',
            name='kalorie_na_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miary',
            name='skrot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
