# Generated by Django 4.2.1 on 2023-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0007_rename_czas_przygotowania_przepis_czas_przygotowania_w_minutach_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miary',
            old_name='skrot',
            new_name='skrót',
        ),
        migrations.RenameField(
            model_name='przepis',
            old_name='zdjecie',
            new_name='zdjęcie',
        ),
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='ilosc',
            new_name='ilość',
        ),
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='id_miary',
            new_name='miara',
        ),
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='id_przepisu',
            new_name='przepis',
        ),
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='id_skladnika',
            new_name='skladnik',
        ),
        migrations.RenameField(
            model_name='skladnik',
            old_name='zdjecie_skl',
            new_name='zdjęcie_składnika',
        ),
        migrations.RemoveField(
            model_name='przepisskladnik',
            name='kalorie_na_100g',
        ),
    ]
