# Generated by Django 4.2.1 on 2023-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Przepisy', '0008_rename_skrot_miary_skrót_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przepisskladnik',
            old_name='skladnik',
            new_name='składnik',
        ),
    ]
